algoan/nestjs-budget-insight-connector

- .helm/budgetinsightconnector/Chart.yaml
- .helm/budgetinsightconnector/templates/deployment.yaml
- .helm/budgetinsightconnector/values.yaml
Mount the volumes in the suitable paths
> [FIX]: fix configmap and secret volumes path

- package-lock.json
- package.json
- views/index.hbs
- Upgrade @algoan/rest version to validate properly the signature
- Update the index file to add the `sha256=` prefix
> fix(deps): upgrade @algoan/rest to validate signature properly

- src/hooks/services/hooks.service.ts
BI base url should be fetched from the the SA if provided.
> [FIX]: Fetch BI baseUrl from the SA configs

- src/aggregator/services/budget-insight/budget-insight.utils.spec.ts
- src/aggregator/services/budget-insight/budget-insight.utils.ts
> [FIX]: Fix account's status

- package-lock.json
- package.json
- src/aggregator/interfaces/budget-insight-mock.ts
- src/aggregator/interfaces/budget-insight.interface.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/budget-insight/budget-insight.client.ts
- src/aggregator/services/budget-insight/budget-insight.utils.ts
- src/algoan/algoan.service.spec.ts
- src/algoan/algoan.service.ts
- src/app.controller.ts
- src/hooks/controllers/hooks.controller.ts
- src/hooks/services/hooks.service.ts
- src/main.ts
- tsconfig.json
- Upgrade @algoan/eslint-config and activate the ts `strictNullChecks` option
- Correct all build and lint issue
> [FIX] Upgrade ESLint and active "strictNullChecks" options

- src/hooks/services/hooks.service.ts
- test/hooks.e2e-spec.ts
- Update SubscriptionEvent status at:
- Reception: `ACK` (acknowledgement)
- Error: `ERROR`
- Failure: `FAILED` (should not happen, the event is not recognized by the connector)
- Documentation [PATCH Resthook Subscription Event](https://developers.algoan.com/api#operation/patchResthookSubEvents)
> [FEAT] Update Subscription event's status

- src/algoan/algoan.service.ts
- test/utils/app.ts
- Set @algoan/rest to use the same Winston Logger config than the rest of the connector
> [FEAT] Use winston logger when calling Algoan

- src/aggregator/services/budget-insight/budget-insight.client.spec.ts
- src/aggregator/services/budget-insight/budget-insight.client.ts
- Make the number of months configurable with the serviceAccount
- Set the default number of months to 5
> [FEAT] make the numberOfMonths configurable

- src/aggregator/interfaces/budget-insight-mock.ts
- src/aggregator/interfaces/budget-insight.interface.ts
- src/aggregator/services/budget-insight/budget-insight.utils.spec.ts
- src/aggregator/services/budget-insight/budget-insight.utils.ts
Map the transaction's currency
> [FEAT] Add mapping for the transaction's currency

- src/aggregator/interfaces/budget-insight.interface.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/budget-insight/budget-insight.client.spec.ts
- src/aggregator/services/budget-insight/budget-insight.client.ts
- src/aggregator/services/budget-insight/budget-insight.utils.spec.ts
- src/aggregator/services/budget-insight/budget-insight.utils.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- Fetch user personal information from the user connection and add the `owner.name` to each account based on its connection (`connection_id`).
- Superseded #59
> [FEAT] Fetch user personal information

- package-lock.json
- package.json
- src/aggregator/interfaces/budget-insight.interface.ts
- src/aggregator/services/aggregator.service.spec.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- Retrieve `clientId` from `ServiceAccount.config` and add it to the `plugIn.budgetInsightBank`
- Update @algoan/rest to 2.0.0 to be able to patch the clientId
> [FEAT] Patch the clientId to the plugIn

- src/aggregator/interfaces/budget-insight-mock.ts
- src/aggregator/interfaces/budget-insight.interface.ts
- src/aggregator/services/budget-insight/budget-insight.utils.spec.ts
- src/aggregator/services/budget-insight/budget-insight.utils.ts
- src/algoan/dto/analysis.enum.ts
- src/algoan/dto/analysis.inputs.ts
- src/hooks/dto/banks-details-required.dto.ts
- src/hooks/dto/event.dto.ts
- src/hooks/dto/index.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
Add a new event handler to retrieve and convert accounts and transactions to Algoan's analysis (accounts and transactions) format.
> [FEAT] Add event `bank_details_required`

- .releaserc.json
- package.json
- Add a specific configuration for the `v2` branch with semantic-release, according to [the workflow configuration](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration)
> chore(releaserc): change semantic-release config

- src/algoan/dto/analysis.enum.ts
- src/algoan/dto/analysis.inputs.ts
- src/algoan/dto/analysis.objects.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
Update the analysis's status and error when encountering an error during fetching data from the aggregator
> Update analysis error when handling `bankDetailsRequired` event

- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/budget-insight/budget-insight.utils.spec.ts
- Generate the logo url from the connector uuid, instead of the id
> [FIX] Logo Url

- package-lock.json
- package.json
- src/aggregator/services/budget-insight/budget-insight.utils.spec.ts
- src/aggregator/services/budget-insight/budget-insight.utils.ts
Description: 
- add field `number` to algoan account
❗️ This PR depends on [this PR on rest-nodejs](https://github.com/algoan/rest-nodejs/pull/46) which adds the new field to account dto/interface.❗️
> [FEAT] add field number to algoan accounts

- src/aggregator/services/budget-insight/budget-insight.client.ts
This pull request aims to add a generic error log when user's JWT token generation failed. This improvement will help monitoring this kind of error.
> [FEAT] add generic error log

- config/default.json
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- Do not wait for the connections in error to change status. 
- Continue the bank data fetching process if there is at least a completed connection
> [FEAT] Enhancements/Fixes in the process

- src/algoan/dto/customer.enums.ts
- src/algoan/dto/customer.objects.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
- test/aggregator-link-required.e2e-spec.ts
- test/utils/algoan.fake-server.ts
* Allow the aggregation in Iframe mode
> [TP-11029] Implement iFrame mode

- .github/workflows/ci.yaml
* Correct the branch of helm chart
> [FIX] Fix Github workflow

- src/aggregator/services/aggregator.service.spec.ts
- src/aggregator/services/aggregator.service.ts
- src/aggregator/services/budget-insight/budget-insight.client.ts
In this PR we made the language customization possible instead of hardcoding french as a language.
> [TP-10326] Make language customizable 

- config/default.json
- config/env/test.json
- src/aggregator/services/budget-insight/budget-insight.client.spec.ts
- src/aggregator/services/budget-insight/budget-insight.client.ts
In this PR, we added a configuration `paginationLimit` to make the pagination limit configurable.
> [FEAT] Make the pagination limit configurable

- src/hooks/services/hooks.service.ts
- The event `service_account_created` cannot be linked to a service account or a subscription already created
> [FIX] fix service account created handler

- src/hooks/services/hooks.service.ts
The service accounts are updated in memory in case a "service_account_created" event is sent. If there is more than one instance of the connector, the service account is not updated in the other instance lists. 
This is a fallback to fetch all the service accounts every time a subscription without SA is received.
> [FIX] Update in memory SA list

- src/aggregator/interfaces/budget-insight.interface.ts
- src/hooks/services/hooks.service.spec.ts
- src/hooks/services/hooks.service.ts
Handle 3 types of error messages:
- Errors from powens (Budget Insight) API 
- Errors from Algoan API 
- Other errors from the connector
> [FEAT] Handle analysis errors better

- src/hooks/services/hooks.service.ts
Remove query params from callback before send it to budget insights
> [FIX] remove query params from callback

- src/aggregator/services/budget-insight/budget-insight.client.spec.ts
This pull request aims to add a commit with feat/fix prefix in order to trigger the deployment of my previous commit.
> [FEAT] fetch account ownerships

- src/hooks/services/hooks.service.ts
This pull request aims to remove sensitive data from logs.
> [FEAT] Logging 
